### ISSUE TITLE
Request error: Old version

### ISSUE THREAD

**Issue by xuanbach4410** [mgp25/WART#10]
WART folder source code when running it and register number , it's give me old version source the api outdate but WART 1.8.1.0 is working fine but I need the source code .. Regards

**Comment by xuanbach4410** [comment]
Source you update using old version: 1.7.1.0

**Comment by mgp25** [comment]
As you said, ver 1.8 is working :)

Regards

**Comment by mgp25** [comment]
Btw, WART code is published

**Comment by xuanbach4410** [comment]
Please see your source, file .exe version 1.8.1
But Source you update version 1.7.1
When i debug, Error old version

**Comment by vovanb** [comment]
version 1.8.2 is working - but latest source code does not.Seems it is not updated.
