### ISSUE TITLE
could not verify existing registration OR could not request code using either sms or voice !!!

### ISSUE THREAD

**Issue by momenimohammad23** [mgp25/WART#11]
hi 
When I open the WART project and Runt it I get this Error ! Old-Version !!!
But when I Use the Release File it work Correctly !!
I want to Customize it , how I can solve it ?

**Comment by xuanbach4410** [comment]
I have same issue

**Comment by momenimohammad23** [comment]
@xuanbach4410  I think the release *.exe file use another whatsappapi 
@mgp25  may you help us 
I need it !

**Comment by xuanbach4410** [comment]
Yes, i think same,
Now, i research it, hope @mgp25 update it

**Comment by xuanbach4410** [comment]
@momenimohammad23 : add my skype: xuanbach4410
We collaborate fix it

**Comment by balapms** [comment]
hi sir my result is status is failed and reason is blocked
