### ISSUE TITLE
Could not request code using either sms or voice. SMS: old_version Voice: old_version

### ISSUE THREAD

**Issue by jawedshaikh** [mgp25/WART#114]
Hi,

I am trying to get password using Wart of a number I enters as input. But I am getting an error:
**Could not request code using either sms or voice. SMS: old_version Voice: old_version** 
Please help me to solve the error as soon as possible.

**Comment by mgp25** [comment]
This code is outdated

Regards

**Comment by jawedshaikh** [comment]
Hi,

Sorry but I did not get how to solve error.
Kindly help me to solve the error or let me know how I can I solve the same.
