### ISSUE TITLE
WART-1.8.1.0.exe contain virus

### ISSUE THREAD

**Issue by Lordfef** [mgp25/WART#12]
Hi, i try to use Wart but the WART-1.8.1.0.exe contain a virus

**Comment by mgp25** [comment]
You idiot? Go check the source code

**Comment by mrjasmir** [comment]
Avast is showing it as virus. Check screen below.

![wartvirus](https://cloud.githubusercontent.com/assets/11965835/7436280/ac290c60-f069-11e4-9011-601983730c68.png)
