### ISSUE TITLE
"Could not connect to remote server"

### ISSUE THREAD

**Issue by g0g0l** [mgp25/WART#16]
What is the possible reason for this? I am trying 1.8.1.0, has the host changed? Can you please look into this?
Thank you

**Comment by mgp25** [comment]
@g0g0l it seems your connection doesn't support SSL. The host, and url hasn't changed, try with other computer if you want, if you still facing the same error, i can register you the number if you want.

Regards

**Comment by g0g0l** [comment]
My bad, there must be some problem with my internet connection. I tried with another internet and it worked. Thank you
