### ISSUE TITLE
Cant request code

### ISSUE THREAD

**Issue by GeradeAtwarp** [mgp25/WART#17]
Hi

I am not able to request a code. I get "old version" error.

Please help.

Thank you.

**Comment by sagarpatil678** [comment]
Hi,
When I execute WART-1.8.1.0.exe, I'm able to request code and generate password.
But when I try to do the same using source code, it is giving me "old version" error.
Can I have the source code for WART 1.8.1.0 version please?

Thanks,
Sagar

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET

**Comment by sagarpatil678** [comment]
Thanks. It's working for me :)

**Comment by GeradeAtwarp** [comment]
Hi @mgp25 

this is still not working for me. Im receiving {\"status\":\"fail\",\"reason\":\"blocked\"} error now when i try to register.

Please help.

**Comment by mgp25** [comment]
@GeradeAtwarp  `reason: blocked`

your number is blocked

**Comment by GeradeAtwarp** [comment]
@mgp25 

Any ideas on how i can unblock it?

**Comment by beljk** [comment]
@it will be block for two months
