### ISSUE TITLE
Register error "reason":"old_version"

### ISSUE THREAD

**Issue by barracuda-arg** [mgp25/WART#2]
Hi everybody! You all people are the best! thank you very much for all your hard work on this project!
I've one question..... I've downloaded the last version of WART and when I run de application and try to either "request code" or "confirm code" always get the same error message:

Could not request code using either sms or voice.
```xml
SMS:    {"status":"fail","reason":"old_version"}
Voice:  {"status":"fail","reason":"old_version"}
```

am I missing something important? I think I do but i just can not figure it out by now....... sorry for my english

Regards from Argentina!

**Comment by mgp25** [comment]
@barracuda-arg send number to my email.

Regards

**Comment by mgp25** [comment]
Its working

**Comment by beljk** [comment]
@mgp25 it's working fine in WART 1.8.0.0.exe but when using the wart source code and run it .. give me old_version .. you can check it when found the output of project source code and the final WART 1.8.0.0.exe it's not the same  .Regards

**Comment by almendieta** [comment]
In my end ONLY 1.8 version worked, but sadly when I tried confirm the code, the application throw the message: verification code not accepted. The problem it's the same in 2 phones I tried. I hope this can be of help. Thanks for your application anyway!

**Comment by barracuda-arg** [comment]
Hi everybody i just wanted to say thanks to mgp25, and wanted to say a few words on this issue, i was able to register my phone number succesfully. well... actually mgp25 did it.... but then i tried with other two phone numbers by my self with script "registertool.php" from whatsapi-oficial and it worked like a charm... of course i had to configure apache and php on my server to run it succesfully but after a couple of hours it got just worked fine. So I didn't try using again WART since march 25th. 

"WART" worked for me a couple of months ago, and "registerTool.php" worked for me a couple of days ago... so.... I think if i would have some trouble on registration again...  i would try using last version of WART as my first option (lattest commit was 7 days ago) and as my second option would try the whatsapi-official script "registerTool.php". 

Best regards!

**Comment by almendieta** [comment]
Hi @barracuda-arg. Can you share your tool or give a link so we can do it too? Thank you in advance!

**Comment by mgp25** [comment]
WART and WhatsAPI Official

**Comment by almendieta** [comment]
Sounds like a lot of work...

**Comment by barracuda-arg** [comment]
Hi almendieta... actually it's not. 

Both tools WART and WhatsAPI-Official are quiet easy to either configure or to use it...  just have to look a little bit into the code.
I´m not to good programmer but if i would have your email i would be glad to help you.

Regards.

**Comment by almendieta** [comment]
Great! Thank you so much @barracuda-arg. Please look at the image for the email.

![em](https://cloud.githubusercontent.com/assets/11827218/7052448/3f97ab9c-ddf4-11e4-84ab-29f15900dc09.png)

**Comment by mgp25** [comment]
WART has an user interface easy to use.

If you want to use `registerTool.php` there is a wiki explaining everything: https://github.com/mgp25/WhatsAPI-Official/wiki
