### ISSUE TITLE
Voice. Request code

### ISSUE THREAD

**Issue by MichaelGrey** [mgp25/WART#21]
I'm sorry but I do not see the possibility of confirming voice
old:
![17777](https://cloud.githubusercontent.com/assets/12447035/7646532/85c80592-fb10-11e4-8dc6-57f0d7d99bcd.jpg)
new:
![18888](https://cloud.githubusercontent.com/assets/12447035/7646540/9b87e8c0-fb10-11e4-9f03-0312f5b0b1b1.jpg)

**Comment by mgp25** [comment]
@MichaelGrey request code, if there is any problem with sms, you will receive a call automatically

**Comment by MichaelGrey** [comment]
My service accepts only voice calls , unfortunately not received a call then .
Maybe add offers voice alerts?

**Comment by mgp25** [comment]
@MichaelGrey if you run WART in command line, you can request code via call

**Comment by letuanht91** [comment]
send mail to me and exchange
Email: anhtuan6751@gmail.com
Whatsapp: 841649637469
