### ISSUE TITLE
Forgotten password cannot be reset

### ISSUE THREAD

**Issue by mutanic** [mgp25/WART#23]
Hi mgp25, currently I am trying to make some changes on your existing program by adding the messaging functionality as Step 3, but I notice there is no way for me to reset back the password if it has been forgotten. I would love to see this function available so easier for user in case the forgot their passkey later. any idea?

![portable whatsapp v2](https://cloud.githubusercontent.com/assets/13059611/8371023/698eb678-1c03-11e5-94a3-b7d6107dcb23.png)

**Comment by mgp25** [comment]
@mutanic The only way to reset a password is knowing your identity, in this case, WART provides a system where a string is sha1 raw encoded and then urlencoded which is being used later as identity, this is the only way to generate the same identity and in consequence to reset the password.

There is no way to recover that identity if you don't know the string = password. An alternative for not forgetting this password, is saving the passwords or the generated passwords in a file, like Chat API does.

If you have any other doubt let me know

Regards
