### ISSUE TITLE
Problems to register

### ISSUE THREAD

**Issue by jmf70** [mgp25/WART#24]
Hi, I'm trying to use WART-1.8.1.0.exe to register a WhatsApp number but it doesn't run on Windows 7 x64, so I downloaded the code to execute it in VS2012 but when I try to register it I receive a fail message due of and old_version.

Do you have any idea or where can i get offcial information about WhatsApp API (if exists :) )?

Thanks for your job, well done.

**Comment by mgp25** [comment]
@jmf70 the source code isn't released, only the executable. Official WhatsApp API is here:

- PHP - Chat API https://github.com/WHAnonymous/Chat-API
- .NET - https://github.com/mgp25/Chat-API-NET

Regards
