### ISSUE TITLE
Auth key is invalid

### ISSUE THREAD

**Issue by fspoficial** [mgp25/WART#25]
I would like to thank for the wart, however, i can't create new whatsapp accounts. The last step in the processes is failing. When i try to put the auth key, generated by wart, the whatsapp servers mark as invalid. I am interested in talk with your team to understand the trouble and solve because my business depends this.

**Comment by mgp25** [comment]
@fspoficial virtual numbers are marked as `invalid` by WhatsApp, try using real phone numbers

Regards

**Comment by fspoficial** [comment]
I am using real numbers, brazilian numbers. You can talk with me in skype? My id: speedio-1. Or whatsapp: +55 11 930188640.

**Comment by fspoficial** [comment]
My whatsapp number: 55 11 930188640. My skype id: speedio-1.




2015-07-07 20:17 GMT-03:00 mgp25 <notifications@github.com>:

**Comment by fspoficial** [comment]
What better way to talk to you?

**Comment by mgp25** [comment]
@fspoficial mail in my github's profile page
