### ISSUE TITLE
Old version , this api out date

### ISSUE THREAD

**Issue by beljk** [mgp25/WART#26]
dear mgp .. WART is out of date (old version)

**Comment by moosaviamir** [comment]
yes dear mgp. its out of date. 
regards

**Comment by mgp25** [comment]
dear @moosaviamir i'll wait for you update

thanks in advance

pss

**Comment by moosaviamir** [comment]
Dear beljk 
I just compiled the WhatsAppApi and uploaded it. just replace the following dll and everything would work like a charm.
Thank you again Dear mgp25 for taking care all of these stufs.
[whatsAppApi.dll](http://s000.tinyupload.com/index.php?file_id=37187916498539188134)

**Comment by mgp25** [comment]
https://github.com/mgp25/WART/commit/ee975f9c79d87da7a725910f7bea85dd235171ca
