### ISSUE TITLE
Whatsapp registration

### ISSUE THREAD

**Issue by jvillal** [mgp25/WART#27]
Hi,

Last week  downloaded the WART tool but when I try to register the new number the application return me back an error: status fail reason old_version.

Thanks for your help.

**Comment by mgp25** [comment]
I update WART today... Check it

**Comment by jvillal** [comment]
Hi,

 

When I try to send a PNG file It shows an error BinTreeNodeReader->readListSize: Invalid token 91

 

protected int readListSize(int token)

        {

            int size = 0;

            if (token == 0)

            {

                size = 0;

            }

            else if (token == 0xf8)

            {

                size = this.readInt8();

            }

            else if (token == 0xf9)

            {

                size = this.readInt16();

            }

            else

            {

                throw new Exception("BinTreeNodeReader->readListSize: Invalid token " + token);

            }

            return size;

        }

 

Any idea?  Thanks.

 

 

 

De: mgp25 [mailto:notifications@github.com] 
Enviado el: martes, julio 21, 2015 11:47 AM
Para: mgp25/WART
CC: jvillal
Asunto: Re: [WART] Whatsapp registration (#27)

 

I update WART today... Check it

**Comment by mgp25** [comment]
This is WART repo, not Chat API Net, go to the proper repository

Regards

**Comment by jvillal** [comment]
Thanks.

---- Mensaje original ---

De: "mgp25" <notifications@github.com>
Enviado: 21 de julio de 2015 3:00 PM
Para: "mgp25/WART" <WART@noreply.github.com>
Cc: "jvillal" <jvillal@msn.com>
Asunto: Re: [WART] Whatsapp registration (#27)

This is WART repo, not Chat API Net, go to the proper repository

Regards

---
