### ISSUE TITLE
not able to send message via whatsapp API using asp.net mvc3

### ISSUE THREAD

**Issue by rajatkumarpati** [mgp25/WART#28]
when i'm trying to send a message using c# with whatsApp API ,

it shows login Failed. The error is not-authorized. Please help me. Thanks in advance.

code:

  WhatsApp wa = new WhatsApp(from, "mypassword", "Rajat", false, false);

        wa.OnConnectSuccess += () =>
            {
                TempData["connect"] = "Connected to whatsapp";

                wa.OnLoginSuccess += (PhoneNumber, data) =>
                    {
                        wa.SendMessage(to, msg);
                        TempData["sent"] = "Message Sent";
                    };
                wa.OnLoginFailed += (data) =>
                    {
                        TempData["fail"] = data;
                    };
                wa.Login();
            };

        wa.OnConnectFailed += (ex) =>
            {
                TempData["failure"] = "Connection Failed";
            };

        wa.Connect();

        return View();

**Comment by mgp25** [comment]
@rajatkumarpati wrong repo

**Comment by isamsuh** [comment]
i have the same issue :S

**Comment by nitkum2** [comment]
when i'm trying to implement this, i ma not able to send message using c# with whatsApp API ,

it shows login Failed. The error is not-authorized. Please help me. Thanks in advance.
 my code is:
string from = "919582734417";
        string To = TextBox1.Text";
        string Msg = TextBox2.Text;
        WhatsApp wa = new WhatsApp(from, "LtPZisN/xLkNd4Wg6y42t+afaQ0=", "Nitin", false, false);

        wa.OnConnectSuccess += () =>
        {

            Response.Write("<script type=\"text/javascript\">alert('Connected to whatsapp');</script>");
            wa.OnLoginSuccess += (PhoneNumber, data) =>
            {
                wa.SendMessage(To, Msg);

                Response.Write("<script type=\"text/javascript\">alert('Message sent');</script>");
            };
            wa.OnLoginFailed += (data) =>
            {

                Response.Write("<script type=\"text/javascript\">alert('Login Failed');</script>");
            };
            wa.Login();
        };
        wa.OnConnectFailed += (ex) =>
        {

            Response.Write("<script type=\"text/javascript\">alert('Connection Failed');</script>");
        };
        wa.Connect();

Please help me out on this issue..
Thanks in advance

**Comment by mgp25** [comment]
@nitkum2 wrong repo
