### ISSUE TITLE
Actiation does not work anymore

### ISSUE THREAD

**Issue by maikeldus** [mgp25/WART#3]
I can request a activation code, and I do recieve it. However, once i try to active it, it says the code is not valid.

Using the executable 1.8.0.0.

**Comment by mgp25** [comment]
@maikeldus if you receive `123-456` you put this: `123456`.

When opening an issue you need to provide as much info as you can in order we can help you.

**Comment by maikeldus** [comment]
It does indeed force only nummeric values in the "confirm code". I tried to re-active with a debug log, but there is a timer of ~30 minutes :(

**Comment by maikeldus** [comment]
```
---------------------------

---------------------------
Code register:
Code = 744353
Number = xxxxxxxxxx
Identity = xxxxxxx
Response = 
---------------------------
OK   
---------------------------
```

So I did not really get a response at all.. The second code also did came from another phonenumber (+1 980 404 2297).

**Comment by mgp25** [comment]
@maikeldus remeber thaat virtual phone numbers are being blocked by whatsapp and also virtual phone number providers

**Comment by maikeldus** [comment]
This is indeed a legitimate phone with WhatsApp already on it, any other leads? Could my IP be blocked, or did that never happened before? I'ts strange to retrieve a empty response (altough, is `Respone = ` a raw output?).

Does it work fine at your end?

**Comment by mgp25** [comment]
@maikeldus 
```
WART.exe request number=19804042297 method=sms
Error:
{"status":"fail","reason":"bad_param","param":"number"}
```

This happens when its a virtual phone number. Or from a unknown providers

**Comment by maikeldus** [comment]
Well the request goes fine, only the confirmation of the code does not work.

**Comment by mgp25** [comment]
@maikeldus try `registerTool.php` from WhatsAPI Official instead.

**Comment by maikeldus** [comment]
That one does work fine, strange issue

**Comment by maikeldus** [comment]
Tried other IP but still no luck, same debug respone: nothing. Also four other people reporting same problem now.

**Comment by m35m3r1z3** [comment]
Hi there,

I had been using WART, youwsup through a 3rd party application and it seems that whatsapp registration is not working for me at the moment,

It used to work with WART and HSM but now, it just states that SMS is sent (I'm using the latest version 1.8.1.0) but it is not working now,

Are you able to help me out with this?
