### ISSUE TITLE
407 error 

### ISSUE THREAD

**Issue by arth1992** [mgp25/WART#30]
Whenever i try to request code i get 407 error Proxy authentication required .
Can i get the solution for this. ?
ASAP

**Comment by 0xTryCatch** [comment]
Relax, we are having weekend too. Sounds like you are behind a proxy server. The API does not work with a proxy server. Try it somewhere else without proxy.

**Comment by arth1992** [comment]
ohk.. enjoy your weekend. I ll try it once again
