### ISSUE TITLE
WART Registration Issue!

### ISSUE THREAD

**Issue by alijundi** [mgp25/WART#32]
Hi @mgp25 

I am trying to register my phone number after all of a sudden I started receiving `UNAUTHORIZED` for my bot that has been online for the past 4 months.

I click on request code or even check existing and without even receiving a code to enter I get the password immediately! I don't really know what this is happening.

Can you please let me know your insight.

Thanks in advance.

AJ

**Comment by WHAnonymous** [comment]
Try `blockChecker.php` if it's not blocked, register again using `registerTool.php` or WART with another password.

Everything is explained here: https://github.com/WHAnonymous/Chat-API/wiki

What happens to you it's normal
