### ISSUE TITLE
Image Message not send

### ISSUE THREAD

**Issue by ppiyushjv** [mgp25/WART#35]
this is my code working in Audio and Video message but not in images so please give me suggetion

            var mp4 = File.ReadAllBytes("D:\\07042010007.MP4");
            var mp3 = File.ReadAllBytes("D:\\titanic_new_version.mp3");
            var img = File.ReadAllBytes("D:\\test.png");
            WhatSocket.Instance.SendMessageImage(txtMobile.Text, img, WhatsAppApi.ApiBase.ImageType.PNG);
            WhatSocket.Instance.SendMessageAudio(txtMobile.Text, mp3, WhatsAppApi.ApiBase.AudioType.MP3);
            WhatSocket.Instance.SendMessageVideo(txtMobile.Text, mp4, WhatsAppApi.ApiBase.VideoType.MP4);

**Comment by mgp25** [comment]
wrong repo
