### ISSUE TITLE
ISsue in HKey generation on WART after 5 HKey Generations

### ISSUE THREAD

**Issue by Tushar999** [mgp25/WART#38]
HI,
I'm facing a problem in WART registration ....Verification code not accepted....after exactly 5 registrations & then it starts working the nest day for more 5 registrations & again same problem...
Also the 6th channel gets blocked immediately without hash key generation....Please guide.

What is debug log??? Please explain

**Comment by mgp25** [comment]
@Tushar999 post debug log, there is an option to activate debug log in the program, paste hear the result.

**Comment by techbro** [comment]
Verification code not accepted.
![screenshot_2](https://cloud.githubusercontent.com/assets/15100485/10446484/e402fcba-719a-11e5-9d07-dc7c4d9aad02.png)

**Comment by techbro** [comment]
This is the debug log serial after & before entering number.
![wart-error](https://cloud.githubusercontent.com/assets/15100485/10447294/f43e6bfe-71a0-11e5-99cb-12b4a9f176cb.png)
![wart-error-2](https://cloud.githubusercontent.com/assets/15100485/10447293/f4332582-71a0-11e5-9627-a4e48d104234.png)
![wart-error-3](https://cloud.githubusercontent.com/assets/15100485/10447295/f44f01e4-71a0-11e5-9f70-faa21476fe7e.png)

**Comment by mgp25** [comment]
Image is self explanatory, read the response.

If you still need more info, read wiki: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#number-registration

**Comment by techbro** [comment]
This error is occurring only for new verification not for old password regeneration..as given in the screenshot.As given in the screenshot it is showing the error it is too early or service temporary unavaible this error should also show for password regeneration but it is working fine & the error is hosing only for new number registration.
Please have a look.
![screenshot_2](https://cloud.githubusercontent.com/assets/15100485/10449549/f246625a-71b1-11e5-8930-9aa679c74d6c.png)

**Comment by mgp25** [comment]
@techbro verification code not accepted == not valid code. Enable debug to see more information
