### ISSUE TITLE
 WART does not accept verification code

### ISSUE THREAD

**Issue by mariamaus** [mgp25/WART#4]
hello,

for almost 4 weeks everything was fine til march 26 when the tracker suddenly went offline. reason: whatsapp had blocked the account. checking the raspberry pi on tv-screen: the =sign from the code was gone, just disappeared.

then tried to registrate a new number (prepaid card) via WART. received the 6-place code from whatsapp (new account), but when I enter that code to WART, in order to receive the generated code ( the long one with the =sign at the end), I get an error message "verification code not accepted"

how can I fix this? what can I do to registrate with a new number? don't know how to use registerscript for activation.

running the newest version of whatsspypublic

thanx in advance
and sorry for mistakes

**Comment by mgp25** [comment]
@mariamaus this is not whatsappspypublic and we dont have any vinculation of it nor support it. For futher support ask to the owner of the repository or use php script from the official repo.

Regards

**Comment by mariamaus** [comment]
ok thank you. 
sorry ...
