### ISSUE TITLE
Could write "Code" (it contains number 10)

### ISSUE THREAD

**Issue by Neubivljiv** [mgp25/WART#41]
This program will work only if Request Code does not contain number 10. I got request code with number ten (10) and WART won't let me to write full request code (it's limited to 6 spaces and number ten have 2 spaces: one and zero). 

Seems that you forgot about this.

**Comment by mgp25** [comment]
![wat](https://i.imgflip.com/tb1fu.jpg)

Request code is 6 digit code, you will receive something like: 123-456

Ir doens't matter if you receive 101-123, it's 6 digit too

**Comment by Neubivljiv** [comment]
Look again image you posted than my comment: :)

Number I received: 4105-6104 
(four ten five - six ten four)

Understand now?

**Comment by mgp25** [comment]
@Neubivljiv thats not possible :/ it could be WhatsApp has extended the code from 6 digit to 8, which is more logic. I'll check

**Comment by mgp25** [comment]
@Neubivljiv post debug log

**Comment by Neubivljiv** [comment]
Could not Request code again (too_recent), but this is debug I received:
![debug](https://cloud.githubusercontent.com/assets/339178/10817464/468eff72-7e3a-11e5-9a7c-18961d19f612.jpg)

**Comment by mgp25** [comment]
@Neubivljiv try with another random number, just to see the debug log

**Comment by Neubivljiv** [comment]
Nothing special...just some "fail" infos
![111](https://cloud.githubusercontent.com/assets/339178/10817560/fddf6388-7e3a-11e5-9947-f53907103e2d.jpg)

**Comment by mgp25** [comment]
@Neubivljiv no, i didnt meant to try a code, i mean to try requesting code with a new random phone number (that exists obviously). Send debug when you have it

**Comment by Neubivljiv** [comment]
Will do when I have time. Currently I am on work...

Regards.
