### ISSUE TITLE
code cannot accepted

### ISSUE THREAD

**Issue by Jay1506** [mgp25/WART#43]
I tried to registering new number by the last WART and I get new code,but that code cannot accepted.
I register new number because my last number can't use with not authorized reason.
why?

**Comment by mgp25** [comment]
@Jay1506 debug log?

**Comment by redstar3** [comment]
same here, I get new code but cannot accepted.
debug log: http://puu.sh/lwWsg/115ab7913a.png
not accepted: http://puu.sh/lwWpR/2a7da097fe.png

**Comment by mgp25** [comment]
You are using virtual phone numbers
