### ISSUE TITLE
Error OldVersion

### ISSUE THREAD

**Issue by ricardoperovano** [mgp25/WART#44]
I'm getting the following error when trying to get password:
"{\"status\":\"fail\",\"reason\":\"old_version\"}"

I'm using the lastest version of wart!
Do you know what could it be ?

**Comment by Dpellekooren** [comment]
I'm also get this error. My whatsapp application stopped with Login failed. Reason: not-authorized. 
When I try to use Wart to get a new version I get: {\"status\":\"fail\",\"reason\":\"old_version\"}

Is there anything I need to update? 

Tnx

**Comment by mgp25** [comment]
without full debug log issue not valid
