### ISSUE TITLE
Status:failed Reason:Blocked

### ISSUE THREAD

**Issue by josiahking** [mgp25/WART#45]
Hello, i am using the lastest version of WART.
After retrieving my password for the first time, i successfully sent a message to a friend using Chat-API library.
But when i try to send to another phone number it didn't send, and was having a login failure exception thrown.
After i tried to get a new password with WART tool i got the message:
{'status':'fail','reason':blocked'}.

**Comment by mgp25** [comment]
You are doing something wrong then
