### ISSUE TITLE
register issues (wart/yowsup)

### ISSUE THREAD

**Issue by lancer97** [mgp25/WART#46]
Hi,

I always get an error using WART and Yowsup even if I used different new sim cards from different telco's and even using different server locations. I got the verification code successfully though, problem is getting the deciphered key. Any help please ,, 

WART - I always get a verification code not accepted 
Yowsup - status fail; reason: temporarily_unavailable

thanks

**Comment by SpotBR** [comment]
I have this issue too, please, i'm needing an update to resolve it!

**Comment by mgp25** [comment]
It works perfectly, at least with my personal number, no virtual phone numbers or similar.

You can use watools or `registerTool.php` instead.

Regards

**Comment by lancer97** [comment]
I tried using that registerTool.php ,, still got the same error  "temporary_unavailable" ;(

**Comment by mgp25** [comment]
@lancer97 your network or mobile provider is blocked/flagged, its working perfectly.

Regards

**Comment by lancer97** [comment]
Oh , but how come if I tried connecting to whatsapp directly using my mobile phone with the same telco its ok? So they (whatapp) knew if I'm using one of the scripts (wart, yowsup) to connect to them as compared to using the mobile app ?

tnx
