### ISSUE TITLE
Whatsapp Verification code not accepted

### ISSUE THREAD

**Issue by drago88** [mgp25/WART#47]
hi. github
I want make c# application to send whatsapp Message...this project already finish 1 month ago...
but today when i login it's says Login failure
so i try use another sim card to register new Cell no.
when i use WART. it's success send me the verification code.. but when i want to confirm.
it's appears failed message...
t
![whatsapp](https://cloud.githubusercontent.com/assets/16268287/11762563/574f69ae-a11d-11e5-9503-4c14228531db.JPG)
![whatsappcode](https://cloud.githubusercontent.com/assets/16268287/11762564/57544afa-a11d-11e5-861a-0d91a11fb2f0.JPG)

so how can i fix this problem.. i already user 3 different SIM card and operator. but it always show same message...

Regard

**Comment by Jay1506** [comment]
So do I tried to register new number by latest wart issuing like this
![picture](https://cloud.githubusercontent.com/assets/12292229/11766207/9f902ab8-a1af-11e5-9128-fb040f471ed6.png)

**Comment by lancer97** [comment]
Hi ,, same here using yowsup ;(

**Comment by lancer97** [comment]
Hi,
Same here ,, ;(

![yowsup](https://cloud.githubusercontent.com/assets/16238647/11838647/52772850-a423-11e5-9a43-c6d38ba19937.png)

**Comment by mgp25** [comment]
@lancer97 you are using youwsup, not the same
@Jay1506 use latest version
@drago88 is that virtual numbers ?

**Comment by drago88** [comment]
@mgp25 I'm using Real SimCard. using latest version of WART. not using yowsup.

**Comment by Jay1506** [comment]
@mgp25 yeah, I used latest version from WART MASTER and appears "code not accepted" like @drago88 's issue.
For you know, I always use real number not virtual number
