### ISSUE TITLE
Whatsapp Verification code not accepted [ Reposted ]

### ISSUE THREAD

**Issue by drago88** [mgp25/WART#48]
hi. github
I'm sorry before for repost this issue. because my last issue was closed before i get the Real Solution

I want make c# application to send whatsapp Message...this project already finish 1 month ago...
but today when i login it's says Login failure
so i try use another sim card to register new Cell no.
when i use WART. it's success send me the verification code.. but when i want to confirm.
it's appears failed message...

- I am Using Last Version of WART.exe. i download it from here. 
- the number i use is real number ( real SIM CARD ). 
here is the prove. 

![capture](https://cloud.githubusercontent.com/assets/16268287/11846353/dff8d2ce-a44a-11e5-87a5-07a34681484f.JPG)
Look at the 6 last digits at sim card.. same as i use for get the Whatsapp Verification code.. but it no Accepted.

![574f69ae-a11d-11e5-9503-4c14228531db](https://cloud.githubusercontent.com/assets/16268287/11845931/d5d1a6ba-a448-11e5-8b32-4176b2ccad4e.JPG)
![57544afa-a11d-11e5-861a-0d91a11fb2f0](https://cloud.githubusercontent.com/assets/16268287/11845943/e1ab1462-a448-11e5-828c-831ae55df679.JPG)

so how can i fix this problem.. i already user 3 different SIM card and operator. but it always show same message...

Regards

**Comment by mgp25** [comment]
Its blocked man, read before post things, there is a lot of documentation i wrote about this and scripts to test if the number is blocked.


```
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 6282366446263


Type sms or voice: sms
Array
(
    [in] => 82366446263
    [cc] => 62
    [id] => j?o??m(.e?~?j}?-y?
    [lg] => id
    [lc] => ID
    [sim_mcc] => 510
    [sim_mnc] => 000
    [method] => sms
    [token] => e4a102e39806d5b3e7afdb9af1c66742
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
There was a problem trying to request the code.
```

**Comment by drago88** [comment]
how can it's blocked ?...in this 3 day i already use more then 5 new sim card,,, but all is same error 
this is new sim card i buy today...

![whatsapp request](https://cloud.githubusercontent.com/assets/16268287/11865626/bf17d91e-a4d7-11e5-8689-064fb4f7793f.jpg)
![error1](https://cloud.githubusercontent.com/assets/16268287/11865628/c18ed058-a4d7-11e5-8f47-ff767536d1e9.jpg)
![error1](https://cloud.githubusercontent.com/assets/16268287/11865630/c4863daa-a4d7-11e5-88b8-84d8a9ae82b2.jpg)

i never user this number for Whatsapp before... it's fresh new number.

**Comment by mgp25** [comment]
First check if the number is blocked. Maybe your network is flagged and blocking all numbers directly

**Comment by drago88** [comment]
How to check if the number is blocked or not?

The point im not understand is.. how can whatsapp blocked new sim card number...
if the number is blocked. it shouldn't send us the Verification number right? but in my case it give text message of verification number. but at step 2 the code whatsapp give me by Text Message it's always Not Accepted..

and if my network is flagged, i already tried using WART at my home and my office.  which is using different Internet service provider and different provider also for the SIM Card. sometime i tried this WART on free wifi area like at cafe. i think i already try using so many different internet provider and so many provider of Sim Card

**Comment by iramadhan** [comment]
I got same issue too, my new phone numbers always blocked by whatsapp,
@drago88  do you already solve this issue?

**Comment by meghamaria90** [comment]
Not able to registaer my number getting an error..see attachment
![error](https://cloud.githubusercontent.com/assets/22542877/18990484/caa09ad8-872f-11e6-87f7-0f3630a38cd9.png)
