### ISSUE TITLE
WART unable to correctly identify phone number

### ISSUE THREAD

**Issue by Daedalusion** [mgp25/WART#49]
Hi

Not sure if I am doing something wrong here. Live in South Africa. When entering my number and pressing 'Request Code' it simply returns no patterns matching for Russia?

Tried debugging the solution, first it comes up with Kazakhstan, then after the country helper is created it somehow ends on Russia and being invalid.

I have my application written and ready to go, just need to get past this password thing. 

When bypassing the checks and manually forcing the number to South Africa I get an old version error.

Looking forward to any responses.

UPDATE

Got the MMC, MNC, Code etc. for South Africa. When manually adding that to the Phone number it seems to pass the check. However the old version error persists.

Using latest distro for WART. Swapped our the Whatsapp API  as I can see there is a newer one. Still get the old version error for some reason.

I see quite a few people mention this issue in forums with no real solution. Where would the problem lie if the latest version of the API was added?

**Comment by mgp25** [comment]
Everything is working perfectly as far as i have seen, if you still face this issue, post debug log and number.

Regards
