### ISSUE TITLE
Verification code not accepted

### ISSUE THREAD

**Issue by Marco208** [mgp25/WART#5]
Hi,

I've tried 1.8.0.0 1.7.1.0 but it doesn't work for both voice and SMS verification. Is there an issue?

**Comment by mgp25** [comment]
@Marco208 yes, there is an issue, use `registerTool.php` from WhatsAPI Official meanwhile

**Comment by Marco208** [comment]
That worked.

**Comment by popkr** [comment]
Hello ...can you make the application save the generated password with number in a text ...and dont close each time ?!

**Comment by RomioVIP** [comment]
Hello why wart 1.8.0.0 not working no more new please

**Comment by mgp25** [comment]
@RomioVIP post full debug log!!!

**Comment by RomioVIP** [comment]
why i can't use voice its only sms working and i don't know more about debug log sorry @mgp25

**Comment by whatsaa** [comment]
hey 

please i want to ask about WhatsAppApi.dll

bcz this dll is get old version

?????????

**Comment by popkr** [comment]
Please update whatsAppApi.dll it gives old_version

**Comment by RomioVIP** [comment]
Please any update its old version also not confirmed sms and can't send call

**Comment by mgp25** [comment]
Can everybody stop bitching?

Ill look this when i have free time.

Just for you to know, if people annoys me, ill close this repo and wont update it again

Best regards

**Comment by RomioVIP** [comment]
ok bro thanx for it i'm sorry @mgp25

**Comment by whatsaa** [comment]
hhhhhhhhhhhhhh fuck this dll

i updated http link


bye bye

**Comment by popkr** [comment]
Whatsaa can you tell me how ?!

**Comment by popkr** [comment]
@whatsaa

**Comment by prinxpronx** [comment]
I have:
"could not request code using either sms or voice.
SMS: status fail blocked
Voice: status fail blocked "
any solution?

**Comment by popkr** [comment]
The number ylu ate using is blocked from whatsapp and please show full
debug log

**Comment by prinxpronx** [comment]
on pidgin I have: "not Authorized"...when I use the WART, when I click on "Request code" I have:

could not request code using either sms or voice.
 SMS: {"status":"fail","reason":"blocked"}
 Voice: {"status":"fail","reason":"blocked"}

where i take this debug log?

**Comment by mgp25** [comment]
@prinxpronx not authorized = blocked

**Comment by prinxpronx** [comment]
oh...And there is any solution?

**Comment by mgp25** [comment]
@prinxpronx nope

**Comment by prinxpronx** [comment]
but, I remember that I had this problem, with the new version of wart, this problem was solved

**Comment by mgp25** [comment]
@prinxpronx wart is up to date

**Comment by prinxpronx** [comment]
ok, thanks anyway

**Comment by reddy4079** [comment]
Wart.exe is not generating the request code..its showing bad token
