### ISSUE TITLE
Old Version on Registry/Check avaliability

### ISSUE THREAD

**Issue by JulioImolesi** [mgp25/WART#50]
Error Old Version at Registry:

![image](https://cloud.githubusercontent.com/assets/14364765/12079006/4c7ed614-b210-11e5-9228-26da0d655ce9.png)
![image](https://cloud.githubusercontent.com/assets/14364765/12079007/5d8b581a-b210-11e5-9354-a5a5de218aaf.png)

And Check Existing:

![image](https://cloud.githubusercontent.com/assets/14364765/12079010/6af9f150-b210-11e5-85b0-1af6794e8d4c.png)

I think that its because the Authentication Method V2 is outdated,

**Comment by mgp25** [comment]
@JulioImolesi its because version must be updated, ill update it, take a look to chat api

**Comment by mgp25** [comment]
@JulioImolesi make sure you are using latest release, or try again, version should be this one in the debug log: 2.13.27

**Comment by JulioImolesi** [comment]
Thankz @mgp25, I just updated the version at ChatNet-API/WhatsConstants.cs (:
