### ISSUE TITLE
WART Obsolete...Referense Issue <https://github.com/mgp25/WART/issues/48> / <https://github.com/mgp25/WART/issues/47> 

### ISSUE THREAD

**Issue by drago88** [mgp25/WART#51]
After using a lot of sim card.. trying to get whatsapp password... and all return error..."Verification Code Not Accepted"
![capture](https://cloud.githubusercontent.com/assets/16268287/12235219/e031e398-b8a4-11e5-9bc8-57a8d93693cf.JPG)

I have tried using this SIM Card at bluestack and it's working perfect... so. it's mean the problem is not at my card or my network is flagged. 

![capture](https://cloud.githubusercontent.com/assets/16268287/12235274/4f3476d4-b8a5-11e5-9433-67a3a1e1f70f.JPG)

I Have tried so many time using REAL SIM Card ( See the picture i Attached ) and all have same Failed Result 

![wa1](https://cloud.githubusercontent.com/assets/16268287/12235311/9897f68e-b8a5-11e5-9e16-8b027c6193e0.JPG)

![wa2](https://cloud.githubusercontent.com/assets/16268287/12235316/9ebaa3c2-b8a5-11e5-8c5e-045084fbe3a1.JPG)

![wa3](https://cloud.githubusercontent.com/assets/16268287/12235323/ab6a0806-b8a5-11e5-8674-501a7bed1a08.JPG)

![wa4](https://cloud.githubusercontent.com/assets/16268287/12235329/b2165a38-b8a5-11e5-9d8b-01185bb97dad.JPG)

So maybe the problem is not at my SIM CARD or my network is Flagged... But this WART is obsolete and need to be fix..

@mgp25 Please contact me skype : mgmcash88  or email me @ pedro.asgardian@gmail.com
i want to start a private chat...

**Comment by rogobob** [comment]
@mgp25 I am having the same issue. Since there were a lot of changes from WhatsApp protocol recently - is this version supposed to work?

I am using tethering to register from different IP addresses and this has worked fine until about a week ago. Only real SIMs used, not virtual.
