### ISSUE TITLE
Verification Code Not Accepted.  Reference Issue < https://github.com/mgp25/WART/issues/51 >

### ISSUE THREAD

**Issue by dbraga88** [mgp25/WART#52]
First of all.. Im sorry for this my last issue. and i have not any intension to offense anybody

This is my last issue.. Because my other user ID has been blocked from this repository without any reason so i created this new id.

![blocked](https://cloud.githubusercontent.com/assets/16686589/12298220/a66a0d20-ba43-11e5-8266-3c7d555fa98e.JPG)

my Issue has been closed by @mgp25 without any solving..this is my issue 
https://github.com/mgp25/WART/issues/48
https://github.com/mgp25/WART/issues/47
https://github.com/mgp25/WART/issues/51
not only me have the same issue..but other people have same issue 
https://github.com/mgp25/WART/issues/46
https://github.com/mgp25/WART/issues/43

the explanation from @mgp25 is just we are using Virtual Number Or Network and Provider have been blocked. but i'm sure that is not the problem. because i'm using Real Number using Real SIM CARD

![wa1](https://cloud.githubusercontent.com/assets/16686589/12297170/7b2ac762-ba3e-11e5-92c0-6cbd762134a3.JPG)
and if my provider or network is flagged.. it will not success on bluestack whatsapp

![wa2](https://cloud.githubusercontent.com/assets/16686589/12297274/f82dcb4c-ba3e-11e5-9934-c3b59487d565.JPG)

so. it's mean there is no problem with my SIM Card and my Network or Provider but the problem is on this WART.exe Please take a look at this picture.

![wa3](https://cloud.githubusercontent.com/assets/16686589/12297332/4c5a52da-ba3f-11e5-967c-2cde670bc897.JPG)
![wa4](https://cloud.githubusercontent.com/assets/16686589/12297338/510e7252-ba3f-11e5-992a-2591a3f7f99b.JPG)
![wa5](https://cloud.githubusercontent.com/assets/16686589/12297342/5508d3ca-ba3f-11e5-9c0f-28be9d181aab.JPG)
![wa6](https://cloud.githubusercontent.com/assets/16686589/12297352/59c71dea-ba3f-11e5-8b99-d954259f9b28.JPG)

I think. this last Version of  WART is already obsolete. and need to be improve..

Thanks for attention

**Comment by mgp25** [comment]
@dbraga88 please answer this simple questions:

- Where are that sim cards from? Provider?
- What do you use the API for and why you have that many sim cards

**Comment by dbraga88** [comment]
@mgp25  Here is my answer :
- Sim Card From Indonesia Provider is Telkomsel, Excel ( XL), Indosat
- The API i use for broadcast our Running promo or Announcement to our registered member. 
- Why i have that many sim cards simply because i try one by one of them for get the password from WART.exe VS Whatsapp at bluestack. all failed at WART but at bluestack whatapp running good.. thats way i realize the problem not at SIM Card or Flagged Provider/Network..Each of Sim Card is buying using different Government ID of my office mate. 
- I need to start a private chat...

Thanks for Attention @mgp25

**Comment by mgp25** [comment]
@dbraga88 do you see now why i locked and closed all your issues? API is only for personal usage.

Regards
