### ISSUE TITLE
I can't register any phone number anymore using WART to get a password

### ISSUE THREAD

**Issue by eman1000** [mgp25/WART#53]
I registerd a number a few days ago using WART and it was working just fine sending whatsapp messages etc, but then it got blocked. I tried to use a new phone number but WART can't register any of the phone numbers. I jus get an error like the one in the screen shot. My numbers just get blocked when I am just trying to register.
![screen shot 2016-01-21 at 8 44 58 pm](https://cloud.githubusercontent.com/assets/16818188/12482652/c20671b0-c08b-11e5-8d03-254c5e05963b.png)

**Comment by mgp25** [comment]
Your number is blocked and there is a big chance that your IP is flaged too, so that's why the insta-blocking

Regards

**Comment by rogobob** [comment]
@eman1000 Use mobile tethering to switch IPs

**Comment by eman1000** [comment]
@mgp25  @rogobob thanx for the reply, i tried to use mobile tethering and another computer to register, After entering the 6 digit activation code i get an error "code not accepted" when i tried again, i got blocked. I tried three different numbers now, they are all blocked.

**Comment by rogobob** [comment]
@eman1000 The "Verification Code Not Accepted" error is a different error and I have no solution to that but it does not always happen for me. Did you try registering the same number you tried before? Because if the number is blocked already it will remain blocked and you can do nothing about it.

**Comment by eman1000** [comment]
@rogobob I have tried a new numbers but they are all blocked now. Last week everything was working just fine i don't what changed. So now when i try a new line i get "Verification Code Not Accepted", when i try again for the second time or third time the number gets blocked. Is there another way to get the whatsapp password?

**Comment by rogobob** [comment]
@eman1000 Using a library like <a href="https://github.com/mgp25/Chat-API">Chat-API</a> or <a href="https://github.com/mgp25/Chat-API-NET">Chat-API-NET</a> where Chat-API appears to be more up-to-date.

**Comment by eman1000** [comment]
@rogobob Okk thanks a lot let me try it out
