### ISSUE TITLE
Can't activate new phone number

### ISSUE THREAD

**Issue by boxgames1** [mgp25/WART#54]
Hi.

I'm trying to register a new phone number with the WART. I receive the SMS in the device, but after insert it in the WART I obtain the following message:

"Verification code not accepted"

I tried several times and receive the same message in each try.

Kind regards.

**Comment by mgp25** [comment]
Without deug log or more info, this issue is invalid. For further support post all the information and debug

**Comment by boxgames1** [comment]
How can I get the debug log from WART application (.exe)?

**Comment by boxgames1** [comment]
Could you help me? I can not get a debug log from the .exe WART.

Thanks.
