### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by hardikcc** [mgp25/WART#55]
Hi,

I have been trying to get the source code working to request code. However, its giving me an error old_version. I have gone through your old issues, however unable to use the code even after replacing dll file. Please guide.

**Comment by mgp25** [comment]
Please post debug log

**Comment by hardikcc** [comment]
https://v.whatsapp.net/v2/code?method=sms&in=9252991029&cc=7&id=a%9fo%cbzp%1b%ca%3b%85%1a%a2%b7%ef%ccz%9eu%b9s&lg=kk&lc=KZ&token=3dbeb4395b02fd6c93742838a8bd8717&sim_mcc=000&sim_mnc=000

Identity - "a%9fo%cbzp%1b%ca%3b%85%1a%a2%b7%ef%ccz%9eu%b9s"
Phone - "9252991029"
User Agent - WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302

**Comment by hardikcc** [comment]
I tried it using the built, its working fine.

**Comment by mgp25** [comment]
@hardikcc you are using an outdated version of WART, use the latest .exe

**Comment by hardikcc** [comment]
Well, its working from the exe but source code is not working.

**Comment by mgp25** [comment]
@hardikcc i haven't released the source code and i won't

**Comment by hardikcc** [comment]
Ok, thanks for response.

**Comment by RamSChoudhary** [comment]
Hello mgp25

I am facing the "old_version" error multiple times. please help me here below is the debug log

Code Request:
Token = c8bedc045589a8a8fecb897dde65a119
Identity = %bf%9b%ff%bfa%b1%81%00%5bu%a7n%5b%e2%a8l%d6%3b%06%2f
User Agent = WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302
Request = https://v.whatsapp.net/v2/code?method=sms&in=15214722311&cc=49&id=%bf%9b%ff%bfa%b1%81%00%5bu%a7n%5b%e2%a8l%d6%3b%06%2f&lg=de&lc=DE&token=c8bedc045589a8a8fecb897dde65a119&sim_mcc=000&sim_mnc=000
Response = {"status":"fail","reason":"old_version"}


Code Request:
Token = c8bedc045589a8a8fecb897dde65a119
Identity = %bf%9b%ff%bfa%b1%81%00%5bu%a7n%5b%e2%a8l%d6%3b%06%2f
User Agent = WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302
Request = https://v.whatsapp.net/v2/code?method=sms&in=15214722311&cc=49&id=%bf%9b%ff%bfa%b1%81%00%5bu%a7n%5b%e2%a8l%d6%3b%06%2f&lg=de&lc=DE&token=c8bedc045589a8a8fecb897dde65a119&sim_mcc=000&sim_mnc=000
Response = {"status":"fail","reason":"old_version"}

Could not request code using either sms or voice.
SMS:    {"status":"fail","reason":"old_version"}
Voice:  {"status":"fail","reason":"old_version"}
