### ISSUE TITLE
Number Blocked

### ISSUE THREAD

**Issue by jaikumarth** [mgp25/WART#56]
Hi,
when ever i register a number using WART after entering the six digit code the number is being banned. What is the solution for this.

**Comment by 0xTryCatch** [comment]
Debug log?

**Comment by jaikumarth** [comment]
i have attached the log when i tried to register using whatsapp from my phone. same error my number is blocked

**Comment by mgp25** [comment]
If you don't post debug log, this is considered as invalid

Regards
