### ISSUE TITLE
Provided number does not match any known patterns for China

### ISSUE THREAD

**Issue by gahlotkrishan** [mgp25/WART#57]
I'm trying to register a new chinese mobile number but getting error.
Number I'm using is +8617078320056

**Comment by mgp25** [comment]
no debug log = invaalid issue

**Comment by ewwink** [comment]
hi @mgp25 I think debug log is not needed, the problem is the number is not match with regex from `AppCode\countries.tsv` I have also the problem my phone number is `62895329768974` (indonesia) does not match. can you tell me how to fix the regex?
thanks

**Comment by Tawabril** [comment]
I have thee same issue too. Can anyone please help?

**Comment by gahlotkrishan** [comment]
It's pretty simple. Just ignore the "CheckFormat" function available in CountryHelper.cs class

**Comment by Tawabril** [comment]
Thanks a great deal team.
I did commented that.But now getting SSL/TSL Trust error issue.
Please note that i am not behind any firewall or proxy.
Please assist.
Thanks 

    On Thursday, April 28, 2016 9:40 AM, gahlotkrishan <notifications@github.com> wrote:
 

 It's pretty simple. Just ignore the "CheckFormat" function available in CountryHelper.cs class—
