### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by jaikumarth** [mgp25/WART#58]
When i try to receive code for a number, i got the error message as
Could not request code either by voice or sms
sms: exception has been thrown by the target of an invocation
voice: exception has been thrown by the target of an invocation

**Comment by mgp25** [comment]
It's working perfectly. You can also try alternatives metioned in the wiki

**Comment by jaikumarth** [comment]
no. alternatives not working. your online tool giving me error as Seems there was an error! We don't support spammers

**Comment by mgp25** [comment]
Unfortunately, we do not support `+91` numbers

**Comment by arunmasq** [comment]
I was registered my +91 number using exampleRegister.php.. But i can't able to login using that password...

**Comment by arunmasq** [comment]
@mgp25 can you help me?
