### ISSUE TITLE
numbers been blocked during registration

### ISSUE THREAD

**Issue by samuelg78** [mgp25/WART#60]
Hi,  is this tool and online WART still working?i got 2 of my numbers been blocked using online WART and 1 number been blocked by this tool.

**Comment by jaikumarth** [comment]
wart is not working tool, wat ever the query we post they simply eyewash and eager to close the issue.
waste of time

**Comment by mgp25** [comment]
Use `registerTool.php` instead

Regards

**Comment by samuelg78** [comment]
@mgp25 Hi, maybe you can put an announcement that tell everybody that the this wart and the online version is not working anymore. At least they can stop registering and stop getting the new numbers been blocked. Thks
