### ISSUE TITLE
Changes in getting password in the last couple of days?

### ISSUE THREAD

**Issue by penta314** [mgp25/WART#62]
During several months I have had no problem at all registering some phone numbers. Everything worked like a charm

Yesterday, I tried to register a new phone, I received the SMS code, but when trying to use it, "old_version" error arised, which I never saw before...

Does it means that Whatsapp has changed something that makes WART (current master) deprecated?

I can provide phone/code(received via sms) privatelly for testing if requested :)

**Comment by mgp25** [comment]
Yes, they changed a couple of things. I'll update eventually, i guess

Regards
