### ISSUE TITLE
WART getting 'old version' error

### ISSUE THREAD

**Issue by oram83** [mgp25/WART#64]
Hi,
I was trying to register a new number to work using the WART. I got an error 'old version'.

**Comment by mgp25** [comment]
post debug log

**Comment by oram83** [comment]
Code Request:
Token = b2f53f1d7b412ffda0fa0e5bf3b8a253
Identity = %eb%2b%92%f4%cd%29%0cx%c29%b7rls%bf%60%1dq%a8%94
User Agent = WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302
Request = https://v.whatsapp.net/v2/code?method=sms&in=536212548&cc=972&id=%eb%2b%92%f4%cd%29%0cx%c29%b7rls%bf%60%1dq%a8%94&lg=he&lc=IL&token=b2f53f1d7b412ffda0fa0e5bf3b8a253&sim_mcc=000&sim_mnc=000
Response = {"status":"fail","reason":"old_version"}

Code Request:
Token = b2f53f1d7b412ffda0fa0e5bf3b8a253
Identity = %eb%2b%92%f4%cd%29%0cx%c29%b7rls%bf%60%1dq%a8%94
User Agent = WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302
Request = https://v.whatsapp.net/v2/code?method=voice&in=536212548&cc=972&id=%eb%2b%92%f4%cd%29%0cx%c29%b7rls%bf%60%1dq%a8%94&lg=he&lc=IL&token=b2f53f1d7b412ffda0fa0e5bf3b8a253&sim_mcc=000&sim_mnc=000
Response = {"status":"fail","reason":"old_version"}

**Comment by mgp25** [comment]
Yes, it seems outdated. Im not sure if ill update it

Regards

**Comment by caccamo88** [comment]
same for me :(

**Comment by rahuls3388** [comment]
Getting same Old_Version error, How to resolve it ?
