### ISSUE TITLE
Error bad token

### ISSUE THREAD

**Issue by rogerxosoft** [mgp25/WART#69]
I have the following problem:

status: fail  reason: bad_token 

please help..

**Comment by mgp25** [comment]
Ill update this eventually, use `registerTool.php`

**Comment by sathishp87** [comment]
Am also getting same error when am trying generate a password. Please let me know how to resolve this.

**Comment by gurupreetkaushik7** [comment]
**Can anyone help me with the bad token error msg? OP. Please help or suggest a work around for this.**
