### ISSUE TITLE
Brazil pattern has changed

### ISSUE THREAD

**Issue by felipebraga** [mgp25/WART#70]
Hi, Brazil phone number has changed.

Now is +55 **9** xxxx xxxx.

Add one more number.

Thanks

**Comment by mgp25** [comment]
@felipebraga use http://watools.es until i update wart

Regards

**Comment by alexandre-mbm** [comment]
@mgp25, it is down!

**Comment by mgp25** [comment]
Yes, i shut it down. You can find that info in google

Regards
