### ISSUE TITLE
"Only variables should be passed by reference" in 'Simple CLI client.php'

### ISSUE THREAD

**Issue by will-code-for-pizza** [mgp25/WART#76]
While running 'php Simple CLI client.php [number]' the screen will be filled up with info message:

PHP Notice:  Only variables should be passed by reference in /root/GIT/vendor/whatsapp/chat-api/examples/Simple CLI client.php on line 33

No real bug, but a little bit anoying.  :-)

Regards.

**Comment by mgp25** [comment]
Wrong repo

**Comment by will-code-for-pizza** [comment]
Ok,.. I will read the documentation twice.
This is what I have done...

# composer require whatsapp/chat-api
Using version ^3.2 for whatsapp/chat-api
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing whatsapp/chat-api (v3.2)
    Downloading: 100%         

Writing lock file
Generating autoload files
root@00001:~# ll
total 52

# cd vendor/whatsapp/chat-api/examples/

Then I run Simple CLI from there...
