### ISSUE TITLE
Austrian country code not supported

### ISSUE THREAD

**Issue by RakouskyS** [mgp25/WART#77]
Numbers start with +43, entering my phone number (43676xxxxxxxx) gives me the error reason "bad_token".

edit: The online version does also not work for my phone number

**Comment by namoo4u** [comment]
same in korea (south)

**Comment by cythrauL** [comment]
Not working for UK number either,

status: fail
reason: bad_token

**Comment by Prabhat36** [comment]
same in india.. plz fix it

**Comment by pradeepsainee** [comment]
It says spammer not supported to me

**Comment by mgp25** [comment]
Use http://watools.es until i update wart

Regards

**Comment by pradeepsainee** [comment]
@mgp25 hi, this is the issue I am getting wile using your online tool  - http://imgur.com/yPjfK8Z
