### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by beljk** [mgp25/WART#8]
new update in whatsapp server .. it's working fine from minutes and now I get reason old version @mgp25

**Comment by mgp25** [comment]
@beljk post debug log.

Regards

**Comment by beljk** [comment]
@mgp25  Sorry sir ... I was working using wart for shiriko not your version .. I test in your update it working fine ...  but what about sending I still use WhatsAppApi for shiriko ... is there difference between you and shiriko api ???

**Comment by mgp25** [comment]
Mine its updated, check repositories
