### ISSUE TITLE
Could not get the code

### ISSUE THREAD

**Issue by raypaullun** [mgp25/WART#86]
Hi , i having issue getting the code from WART and the website watools.es. They send me  the veritification code to my phone, but when ii place code in the website , it didn't return me any code back. As i am doing this c# for project in asp.net , ii cannot use php chat api. Do u have ang solutions?

**Comment by mgp25** [comment]
If you request code in wart, register in wart. If you request coed in watools, register it in watools.

I dont think ill ever update WART, maybe last update eventually, but no promises

Regards
