### ISSUE TITLE
WATools website bans numbers?

### ISSUE THREAD

**Issue by iadj** [mgp25/WART#87]
I just tried to activate a new SIM Card with WATools, and I get the message 'Number or IP is blocked'.

Then I tried to activate it using my own script (Chat-API) and I get an undescribed error: `There was a problem trying to request the code.`

Is there something up with the Whatsapp service or is the hosted tool no longer good?

**Comment by alectu** [comment]
Don't worry man, the stupid admin will close it and send you to the WIKI without any USEFULL information.

**Comment by JasonH0** [comment]
got banned 2..... useless tool....

**Comment by ceghap** [comment]
my number already been banned by whatsapp after using  http://watools.es/pwd.html this website. try to login to my whatsapp on the phone. the apps response that my number already been banned. thanks.
