### ISSUE TITLE
Request Code Not Working 

### ISSUE THREAD

**Issue by brittson** [mgp25/WART#9]
Hi I am getting this Error 
```
Could not request code using either sms or voice.
SMS: {"status":"fail","reason":"old_version"}
Voice: {"status":"fail","reason":"old_version"}
```

**Comment by mgp25** [comment]
@brittson post full debug log

**Comment by popkr** [comment]
@brittson did you get any souloution ?!

**Comment by mgp25** [comment]
Post full debug log so i can see whats happening

**Comment by popkr** [comment]
Here is the debug log

**Comment by mgp25** [comment]
@popkr where?

**Comment by popkr** [comment]
here
![capture](https://cloud.githubusercontent.com/assets/12003741/7387314/6429d598-ee5c-11e4-8006-296dba022151.PNG)

**Comment by popkr** [comment]
please update as soon as possible :)

**Comment by mgp25** [comment]
@popkr why do you need it?

**Comment by popkr** [comment]
To get info to login to wazzup

**Comment by mgp25** [comment]
Send you your number and ill give you the password

**Comment by popkr** [comment]
17728001298 ty :*

**Comment by popkr** [comment]
i got the code :) how can i get the hash ?!

**Comment by mgp25** [comment]
@popkr send it to me by email, ill send you back password and id

**Comment by brittson** [comment]
its only for certain numbers

**Comment by m35m3r1z3** [comment]
Hi there,

I had been using WART, youwsup through a 3rd party application and it seems that whatsapp registration is not working for me at the moment,

It used to work with WART and HSM but now, it just states that SMS is sent (I'm using the latest version 1.8.1.0) but it is not working now,

Are you able to help me out with this?

**Comment by Drorby** [comment]
Hi
where can I download WART 1.8 ?
I have 1/7 version but i get the same error like brittson.

Tahnk u

**Comment by NileshPatilManorama** [comment]
@mgp25 

Hi,

i went with all the vision of wart , But still i'm not able to get the code for my no . Please help me ..

**Comment by WHAnonymous** [comment]
Post debug log, always post debug log!

**Comment by khanak2009** [comment]
Same Error.. :( Will you please send me id and Password for my mobile# 923224041076?

**Comment by khanak2009** [comment]
![screen](https://cloud.githubusercontent.com/assets/19725268/15771431/1ef6c77e-2984-11e6-9681-0fce42eb8880.PNG)

**Comment by mejay4u** [comment]
@mgp25  Getting the same issue can you provide me a password its for my collage project plese help tommorow is my final demoo my number is 917709376242 and email id is mejay4u@hotmail.com pls help thank you
