### ISSUE TITLE
Project is dead / unsupported?

### ISSUE THREAD

**Issue by ildar** [mgp25/WART#95]
Hi!
the latest commit is almost 1 year old, users (incl.me) get bad_token error.
Is the project dead / unsupported?

**Comment by mgp25** [comment]
More or less

**Comment by ildar** [comment]
Then it seems yowsup has no more competitors among offline tools

**Comment by Hichamland** [comment]
if I click on request code I get bad token...:

Could not request code using either sms or voice.
SMS: {"status":"fail","reason":"bad_token"}
Voice: {"status":"fail","reason":"bad_token"}

plz help me
